package com.smarttraining.analytics.enums;

public enum LearningEventType {
    TRAINING_OPENED,
    MODULE_OPENED,
    LESSON_OPENED,
    LESSON_COMPLETED,
    RESOURCE_OPENED,
    RESOURCE_COMPLETED,
    VIDEO_OPENED,
    PDF_OPENED,
    SCORM_OPENED,
    SCORM_FAILED,
    SCORM_PASSED,
    SCORM_COMPLETED,
    SCORM_COMMITTED,
    SCORM_STARTED,
    QUIZ_STARTED,
    QUIZ_SUBMITTED,
    QUIZ_PASSED,
    QUIZ_FAILED,
    SCORE_RECORDED,
    REVIEW_CREATED,
    FEEDBACK_CREATED,
    HELP_REQUESTED
}