package com.smarttraining.analytics.enums;

public enum LearnerNotificationType {
    SUPPORT_SESSION_CREATED,
    SUPPORT_SESSION_UPDATED,
    SUPPORT_SESSION_CANCELLED,
    SUPPORT_SESSION_SCHEDULED,
    TRAINING_INVITATION,
    TRAINING_ASSIGNED,
    DEADLINE_ASSIGNED,
    ACCESS_REQUEST_DECISION,
    FEEDBACK_RESPONSE,
    ACCOUNT_DELETION_REQUESTED,
    ACCOUNT_DELETION_STATUS_UPDATED
}
