package com.smarttraining.analytics.enums;

public enum RiskFactorType {
    NO_ACTIVITY_YET,
    LOW_PROGRESS,
    LOW_QUIZ_SCORE,
    QUIZ_FAILED,
    INACTIVITY_AFTER_START,
    FEEDBACK_DIFFICULTY,
    HELP_REQUESTED,
    VIDEO_NOT_COMPLETED,
    SCORM_NOT_COMPLETED,
    SCORM_FAILED,
    LOW_RESOURCE_ACTIVITY,
    MULTIPLE_RETRIES,
    NO_RECENT_ACTIVITY,
    POSITIVE_PROGRESS,
    GOOD_SCORE,
    RECENT_ACTIVITY
}